// Password hash - injected at build time from GitHub Secrets
// DO NOT commit the actual password hash to the repository
// This file is generated by GitHub Actions from password-hash.js.template
// For local development, use a placeholder or set your own hash
export const PASSWORD_HASH = 'PLACEHOLDER_PASSWORD_HASH';

